/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AgregarTipoFrm.java
 *
 * Created on 15/04/2012, 03:27:54 PM
 */
package easybusmedellinadministrador.Vistas;

import easybusmedellinadministrador.Control.TipoCtrl;
import javax.swing.JOptionPane;

/**
 *
 * @author Edgardo
 */
public class AgregarTipoFrm extends javax.swing.JFrame {

    /** Creates new form AgregarTipoFrm */
    
    private MenuPrincipal menu;
    private final String TITULO = "Error.";
    private final int MENSAJE_ERROR = JOptionPane.ERROR_MESSAGE;
    private final int MENSAJE_INFO = JOptionPane.INFORMATION_MESSAGE;
    private final String CAMPOS_INCOMPLETOS = "llenar correctamente los campos tipo.";
    private final String ACEPTADO= "La Informacion se ha ingresada exitosamente.";
    private TipoCtrl ctrl;
    
    public AgregarTipoFrm(MenuPrincipal menu) {
        this.menu = menu;
        ctrl = new TipoCtrl();
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAgregar = new javax.swing.JButton();
        BtnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Tipo Transporte")));

        BtnAgregar.setText("Agregar Tipo");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnMenu.setText("Menu Principal");
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo(*)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(BtnAgregar)
                .addGap(31, 31, 31)
                .addComponent(BtnMenu)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregar)
                    .addComponent(BtnMenu))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
    this.setVisible(false);
    menu.setVisible(true);
}//GEN-LAST:event_BtnMenuActionPerformed

private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
    
    if(txtTipo.getText().isEmpty()){
        showMessageError(CAMPOS_INCOMPLETOS); 
        return;
    }
        try {
            ctrl.insertarTipo(txtTipo.getText());
            showMessageInfo(ACEPTADO); 
            txtTipo.setText("");
        } catch (Exception ex) {
            showMessageError("Error");
            System.out.println(ex.getMessage());
        }
}//GEN-LAST:event_BtnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
    private void showMessageError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, TITULO,  MENSAJE_ERROR);
    }

    private void showMessageInfo(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "INFORMACION", MENSAJE_INFO);
    } 

}
